### ISSUE TITLE
Posible bug in fill_serialno_fixed.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#100]
**Describe the bug**
[Stm32 manual](https://www.st.com/resource/en/datasheet/cd00237391.pdf) specify 96 bits for device ID but there is only 64 reserved to read the value https://github.com/skycoin/hardware-wallet/blob/04c95ac655b34ee2cfa91fbba9e809048a36bf0a/tiny-firmware/serialno.c#L31

**Environment information:**
Any

**Possible implementation**
Change size to 12 bytes.

**Comment by olemis** [comment]
shall be rescheduled after milestone 1

**Comment by olemis** [comment]
fixed in b469846
