### ISSUE TITLE
Links from readme page are not working

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#102]
**Describe the bug**
The links from the [toc](https://github.com/skycoin/hardware-wallet/tree/develop#table-of-contents) are not working.

**Environment information:**

- GitHub

**Steps to Reproduce**
Go to the [github project page](https://github.com/skycoin/hardware-wallet/tree/develop#table-of-contents).

**Actual behavior**
Not working

**Expected behavior**
Go from toc to topics.

**Possible implementation**
Look at FAQ [here](https://github.com/simelo/skycoin-hardware-wallet/blob/stdevAlDen_t88_seed_generation_entropy_source_questions/README.md#table-of-contents).

**Comment by olemis** [comment]
fixed in e9ae512
