### ISSUE TITLE
Incorrect button orientation

### ISSUE THREAD

**Issue by Dawn-Piper** [skycoin/hardware-wallet#11]
The ok and cancel buttons on the hardware are opposite to what is expected from the software.

**Comment by mpsido** [comment]
Use REVERSE_BUTTON compilation flag to invert button positions.
See [this section](https://github.com/skycoin/hardware-wallet/tree/master/tiny-firmware#2-how-to-compile-firmware) in the README file. It is at the end of the chapter.

Please close this issue it this answer is satisfactory

**Comment by mpsido** [comment]
pushed a file releases/skycoin_reverse_buttons.bin in which the buttons are reversed.

**Comment by mpsido** [comment]
since commit ae2731728f9af21a4b6e272b22e913198cb2954e the butons are inverted by default
