### ISSUE TITLE
Decimals are not being displayed when previewing a transaction

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#111]
**Describe the bug**
When creating a transaction, the device screen only shows the whole part of the amount of coins the user wants to send. For example, if when trying to send 1.5 coins, the screen simply shows 1.

**Environment information:**

- OS: all
- Platform: all
- Firmware Version: develop branch, updated to  4aa0d53.

**Steps to Reproduce**
Create a transaction sending fractions of a coin.

**Actual behavior**
As described at the beginning.

**Expected behavior**
The hardware wallet should show decimals.

**Additional context**
Decimals worked correctly before, so there was probably a problem with some commit added to the develop branch after https://github.com/skycoin/hardware-wallet/pull/93 was merged.

**Comment by stdevStark** [comment]
How can I use SkyWallet from desktop wallet ?

**Comment by stdevIvr** [comment]
![Screenshot from 2019-03-22 18-00-18](https://user-images.githubusercontent.com/45135069/54855683-be867400-4ccd-11e9-8a6c-b27772b46ac2.png)

It works for me.....

**Comment by stdevIvr** [comment]
Ohh, I see. My case works fine, but when I tried 1.5 I only got 1...

**Comment by olemis** [comment]
fixed by bd9320e

**Comment by Senyoret1** [comment]
> 
> 
> How can I use SkyWallet from desktop wallet ?

@stdevStark sorry for the late response.

For compatibility with the hardware wallet to be enabled, you must rebuild the front-end running `npm run build-prod-hw` in `src/gui/static` and then rebuild the Electron executable.
