### ISSUE TITLE
Use protobuf message definitions from a git submodule

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#112]
**Feature description**

Remove the `protobuf`  definitions from the project and use this as a `git submodule`

**Is your feature request related to a problem? Please describe.**
https://github.com/skycoin/hardware-wallet-js/issues/67

**Describe the solution you'd like**
Just remove the `protobuf` related files and use it as a `git submodule` from http://github.com/skycoin/hardware-wallet-protob/

**Additional context**:
- https://github.com/skycoin/hardware-wallet-js/issues/67
- And the same for [hw-go](http://github.com/skycoin/hardware-wallet-go).

**Comment by olemis** [comment]
fixed by 5265050
