### ISSUE TITLE
Reuse protobuf installations commands from hardware-wallet-protob

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#116]
**Feature description**

Protobuf related tools should be installed from https://github.com/skycoin/hardware-wallet-protob.git submodule.

**Is your feature request related to a problem? Please describe.**
TO be consistent with this: https://github.com/skycoin/hardware-wallet-protob/issues/16

**Describe the solution you'd like**
Remove installations instructions from this repository and use it from hardware-wallet-protob.

**Describe alternatives you've considered**
Only this.

**Additional context**
https://github.com/skycoin/hardware-wallet-protob/issues/16

**Possible implementation**
Just remove the installation instructions and use it from hardware-wallet-protob `git submodule`

**Comment by olemis** [comment]
fixed by b62b076
