### ISSUE TITLE
Generating mnemonic with 17 words

### ISSUE THREAD

**Issue by stdevIvr** [skycoin/hardware-wallet#119]
**Describe the bug**
The firmware for the wallet is allowing to work with mnemonics of 17 words, when it should accept only 12 or 24 words.

**Environment information:**

- OS: Linux
- Platform: Linux 4.15.0-46-generic x86_64
- Firmware Version: 1cbb340

**Steps to Reproduce**
* Go to the [skycoin/hardware-wallet](https://github.com/skycoin/hardware-wallet/) repository and run the emulator
* Go to the latest commit in the head (**git checkout 7a4164**)
* Go to [my repo](https://github.com/simelo/skycoin-hardware-wallet-js/tree/stdevIvr_t38_tests_with_mocha_and_chai)
* Install all the dependencies (**npm install**)
* Go go the latest commit (**git checkout 26b075**)
* Run the message's test: **./node_modules/.bin/mocha ./test/messages-test.js**
* Press the OK button in the emulator (right arrow) until the test ends.
* See that the tests are failing because the firmware is accepting 17 words mnemonics.

**Actual behavior**
The tests are failing because the firmware is accepting 17 words mnemonics

**Expected behavior**
The tests should pass properly. In other words, the firmware must only accept 12 or 24 words mnemonics.

**Comment by jdknives** [comment]
The firmware should accept 12, 15, 18, 21, 24. The 12/24 limitation will be handled by the UI only. We should not modify the BIP39 from Trezor. Any modification is a violation of the BIP39 spec.

**Comment by olemis** [comment]
> The firmware should accept 12, 15, 18, 21, 24. The 12/24 limitation will be handled by the UI only. We should not modify the BIP39 from Trezor. Any modification is a violation of the BIP39 spec.

for the record , inherited code only supports mnemonic lengths of 12 , 18, and 24 .

**Comment by jdknives** [comment]
The orginal Trezor code only supports 12, 18 and 24?

**Comment by olemis** [comment]
Neither the [crypto API](https://github.com/trezor/trezor-crypto/blob/master/bip39.c#L119-L121) nor [firmware messages](https://github.com/trezor/trezor-mcu/blob/44bb5864d42e95bb5c15a351f21792df83f4fc61/firmware/fsm_msg_common.h#L349).

Nonetheless this issue is not about implementing specific word count values , but about a critical bug in firmware that leads to generating 24 words mnemonic if a value different than 12 is specified.

**Comment by olemis** [comment]
Thanks @stdevIvr for reporting this . The fact that you found this is a proof of the good work improving the test suite . Has it been completed ? Should you find further bugs please report them to decide when to fix them . Low severity bugs should not make it into milestone 1 .

**Comment by olemis** [comment]
[...]
> a critical bug in firmware that leads to generating 24 words mnemonic if a value different than 12 is specified.

Expected result is sending failure message .

**Comment by gz-c** [comment]
ok 12,18,24 is fine if libbip39 does it

**Comment by gz-c** [comment]
https://github.com/trezor/trezor-crypto/blob/master/bip39.c

see mnemonic_generate

12,15,18,21,24 words are allowed, corresponding to 128,170,192,224,256 entropy bits

**Comment by olemis** [comment]
fixed in af9523f
