### ISSUE TITLE
[Hardware Wallet]: Lock device msg

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#12]
After pressing the left button of the wallet for a few moments, this message appears:
![lock](https://user-images.githubusercontent.com/34079003/46379463-cd6c6200-c66c-11e8-9993-76250103a5ae.png)
The message should probably not say TREZOR.

**Comment by mpsido** [comment]
commit 4ab8855aaa79367575e57555f0a82c3ce0f83ed2
