### ISSUE TITLE
Deactive the method for signing generic messages

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#123]
The method for signing generic messages (the one called with `devSkycoinSignMessage` in the JS library) should be deactived for V1, since it is not used anywhere.

**Describe alternatives you've considered**
https://github.com/skycoin/hardware-wallet/issues/77 , but deactivating it is better for V1.

**Comment by olemis** [comment]
No need to disable since code in `develop` branch protects message signing by pin code .

**Comment by olemis** [comment]
@Senyoret1 if you try it and get a different result let me know . Tested manually with hw-go library .

**Comment by Senyoret1** [comment]
@olemis It is true that the pin code is requested before being able to sign a generic message, but there are problems with that. The user may decide not to use a pin code, and in that case the device must continue being safe. Also, if the user recovers an old seed and then creates a pin code, the device stays without pin for some time, time in which it would be vulnerable.

The Trezor devices always ask for confirmation defore signing generic messages. most likelly for the previous reasons.

**Comment by olemis** [comment]
> The Trezor devices always ask for confirmation defore signing generic messages. most likelly for the previous reasons.

This is what will be done . See #77 .

**Comment by olemis** [comment]
I agree with all your arguments above .

**Comment by Senyoret1** [comment]
Well, asking for confirmation is better, this issues was created just in case deactivating the method was faster than asking for confirmation. Now that this issue is closed, #77 should be added to V1.

**Comment by Senyoret1** [comment]
Hmm, I dont know why Github unassigned @stdevStark with my last comment :frowning:

**Comment by olemis** [comment]
> Hmm, I dont know why Github unassigned @stdevStark with my last comment 😦

nothing you did yourself , everything will be fine once @stdevStark will deal with account configuration issues .

**Comment by stdevStark** [comment]
@olemis I did 2FA . I need to do something to join ?
