### ISSUE TITLE
Enhanced emulator

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#126]
**Feature description**

Implement a more realistic emulator

**Is your feature request related to a problem? Please describe.**
Current emulator is substantially different from firmware binary.

**Describe the solution you'd like**
Implement an emulator that:

- [ ] Runs firmware ARM instructions
- [ ] Virtualizes an USB connection
- [ ] Identifies itself like Skywallets (e.g. via usb , hid , udev in GNU/Linux)
- [ ] Simulates MCU features like MPU , PCROP, RDP , status bits , ...

**Describe alternatives you've considered**
No candidates so far ...

**Additional context**
It might not be feasible to implement some of the features requested .

**Comment by RomanMilishchuk** [comment]
Too much time should be wasted to develop it.
