### ISSUE TITLE
[emulator] Unexpected code on the screen after backup

### ISSUE THREAD

**Issue by stdevIvr** [skycoin/hardware-wallet#131]
**Describe the bug**
There are some characters on the emulator's screen after calling the `devBackupDevice` function.

**Environment information:**

- OS: Linux
- Platform: Linux 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64
- Firmware Version: Don't know...

**Steps to Reproduce**

1. Clone [this](https://github.com/skycoin/hardware-wallet) repo (develop branch)
2. Run `make clean` and then `make run-emulator`
3. Clone [this](https://github.com/simelo/skycoin-hardware-wallet-js) repo (at master)
4. Set to `testTransactionSign = false` and `testBackup = true`
5. Run `node test_codes.js`
6. Either you get error or success, you will see after the whole process, the error on the screen.

**Actual behavior**
Look at this picture:

![Screenshot from 2019-03-17 00-35-44](https://user-images.githubusercontent.com/45135069/54485458-37f61080-484f-11e9-99cb-963db0ae8db9.png)

**Expected behavior**
There is no reason for that sequence to appear on the screen.

**Additional context**
The sequence that appears on the screen is different every time, at least for me.

**Comment by stdevAlDen** [comment]
@stdevIvr this is the device id, will be replaced by a the device label when you set up one.
@jdknives please consider closing this

**Comment by olemis** [comment]
UUID read from device , fixed in b469846
