### ISSUE TITLE
Fix the position of the question mark

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#132]
When confirmation is requested for changing the label or language, the question mark is in an incorrect position (it should not be in a new line, but in the same line of the label):

![hw](https://user-images.githubusercontent.com/34079003/54497392-8d263680-48d0-11e9-8668-7fb8eca3592f.png)

**Environment information:**

- OS: all
- Platform: all
- Firmware Version: develop branch cb522ac (last commit at this time)

**Steps to Reproduce**
Use the `devApplySettings` function of the JS library (or Go cli equivalent) to change the device label.

**Actual behavior**
Explain the failure modes and effects, everything indicating the existence of the bug.

**Expected behavior**
The question mark should be in the same line of the label.

**Comment by stdevAlDen** [comment]
This is ok as is, @gz-c pls open again if  you disagree.
