### ISSUE TITLE
Screen text cut after firmware upload

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet#134]
**Describe the bug**
Text not fully displayed after firmware update.
![2019-03-18 20 50 18](https://user-images.githubusercontent.com/8619106/54541242-888c7b80-49bf-11e9-9f22-cd6937492cd3.jpg)

**Environment information:**

- OS: any

**Steps to Reproduce**

1. Update firmware

**Actual behavior**
text cut around borders

**Expected behavior**
un-cut text

**Possible implementation**
Shorten message to just say `wallet` instead of `Skycoin wallet`

**Comment by stdevAlDen** [comment]
@therealssj maybe it's a duplicate of https://github.com/skycoin/hardware-wallet/issues/83

**Comment by therealssj** [comment]
oh yeah. 
@stdevAlDen maybe update that issue with the image? Closing this one

**Comment by stdevAlDen** [comment]
> maybe update that issue with the image? Closing this one

sorry I no understand you, #83 currently have an img, so what do you mean?

**Comment by stdevAlDen** [comment]
> > maybe update that issue with the image? Closing this one
> 
> sorry I no understand you, #83 currently have an img, so what do you mean?

ok, closed...
