### ISSUE TITLE
Do not change the language if it is not necessary

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#135]
**Describe the bug**
When the [devApplySettings](https://github.com/skycoin/hardware-wallet-js/blob/master/DOCUMENTATION.md#devapplysettings) function of the JS library is called, it is possible to send `null` in the `usePassphrase` and `deviceLabel` parameters to avoid making changes to that configuration elements. For example, I can send `null` in the `usePassphrase` param and `"test"` in the `deviceLabel` param and the hardware wallet will only ask if I want to change the device label. However, it is not possible to do this with the language.

The `devApplySettings` function does not accept a parameter for the language, so it always sends an empty string and the device always asks if the lenguaje should be changed to English. That is ok, but if the library code is modified to send always `null` it shoud do nothing (the lenguaje should not be changed and the device should not ask for confirmation), just as it happens with the passphrase protection and the label. However, what happens is that the device responds as if the operation was performed correctly but in reality no change is made and confirmation is not requested.

This change is necessary because, if it is not done, the user will always be asked to confirm a language change that was not requested, which can be perceived as an operating error.

**Environment information:**

- OS: all
- Platform: all
- Firmware Version:develop branch cb522ac (last commit at this time)

**Comment by olemis** [comment]
fixed in 301feff
@Senyoret1 please try again . Feel free to reopen this issue if you still notice this issue.

**Comment by olemis** [comment]
> The `devApplySettings` function does not accept a parameter for the language, so it always sends an empty string and the device always asks if the lenguaje should be changed to English

JFTR , support for language in js lib is beyond the scope of this repository .

**Comment by Senyoret1** [comment]
@olemis It is working well now :+1: . During the tests I found another problem, but it is different, so put it in https://github.com/skycoin/hardware-wallet/issues/146
