### ISSUE TITLE
Add more salt sources to compute internal entropy

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#141]
**Describe the bug**
The entropy pool mixer needs salt sources
- [x] Clock/systime (if available on the stm32 chip)
- [x] Some global incrementing program counter
- [x] MCU status registers
- ~Temperature sensor~ postponed ... see #162 
- ~RTC registers~ see #206 
- Any variable source of data available to the device other than the rng itself
  * [x] Unconnected GPIO pin

**Environment information:**

Any

**Steps to Reproduce**
Consult [parent issue](https://github.com/skycoin/hardware-wallet/issues/121#issuecomment-471236023) for more details.

**Actual behavior**
Having few salt sources for internal entropy.

**Expected behavior**
Salt sources should ensure that globally unique values are mixed to conform device internal entropy.

**Additional context**
This issue is a continuation of #121 . As a continuation to that one :

- [x] Request and mix external entropy out of band after a given numbers of clock tick counts .

**Possible implementation**
Can be tricky, not support in libopencm3 for reading ADC https://github.com/libopencm3/libopencm3/commit/3eaeaf693c02eba7aee0119d37c1dff3b16b4765

**Comment by olemis** [comment]
I will edit the description of this issue since it is not about entropy sources , but salt .

**Comment by olemis** [comment]
> Can be tricky, not support for adc stm32 series f2 from libopencm3 [libopencm3/libopencm3@3eaeaf6](https://github.com/libopencm3/libopencm3/commit/3eaeaf693c02eba7aee0119d37c1dff3b16b4765)

We'll have to be done from scratch then .

**Comment by gz-c** [comment]
I see the important comment about "variable" is crossed out:

For "variable", there are a few meanings:
 1. variable between devices (such as device UUID)
 2. variable between device runs (at init time)
 3. variable over time (after init, value continues to change)

On PCs:
1. example is env vars
2. example is process id and unix time
3. example is unix time

If a value is only variable in (3) and not (1) or (2) (i.e. every device has the same value on init) then it is not useful unless we periodicially mix it in to the entropy pool.

If there is no/low cost to sampling a variable (3) value, you can sample it every time new entropy is requested. Then (1) and (2) only need to be sampled on init or the first request

**Comment by gz-c** [comment]
And, for difficult to obtain salts, I had said this:

Use as many variable sources of data as you can, **within reason (i.e. not exceptionally difficult to acquire)**

**Comment by gz-c** [comment]
An example of something "within reason" is a simple function call or memory read

**Comment by olemis** [comment]
@gz-c other possible salt sources

| Address range  |  Memory-mapped registers |
|----------------|--------------|
| 0xE000E010-0xE000E01F | System timer |
| 0xE000E100-0xE000E4EF | Nested vectored interrupt controller |
| 0xE000ED00-0xE000ED3F | System control block |
| 0xE000ED90-0xE000ED93 | Memory protection unit |
| 0xE000EF00-0xE000EF03 | Nested vectored interrupt controller |

**Comment by olemis** [comment]
most of these would require privileged mode access

**Comment by stdevStark** [comment]
@olemis this needs that I have a device .

**Comment by olemis** [comment]
right

**Comment by olemis** [comment]
fixed in cde6940
