### ISSUE TITLE
Developer contribution guidelines

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#159]
Continue developer instructions started in https://github.com/simelo/skycoin-hardware-wallet/blob/stdevIvr_t142_refactor_fsm.c_for_unit_testing/CONTRIBUTING.md .

- [x] Go over the test writing procedure and verify that this is working
- [x] Add sections for other parts of the codebase
- [x] Add general Skycoin development policies as applicable
- [x] CLA signing policies
- [x] Relationship to other projects

**Comment by jdknives** [comment]
@olemis do you have specific things in mind that you would like added here?

**Comment by olemis** [comment]
> @olemis do you have specific things in mind that you would like added here?

There are quite a few items in the [project tree overview](https://github.com/skycoin/hardware-wallet/blob/develop/CONTRIBUTING.md#quick-overview) and only bootloader and firmware covered in the docs.

**Comment by olemis** [comment]
@YuraYelisieiev progress ?

**Comment by YuraYelisieiev** [comment]
@olemis added guide on how to compile the whole project and now I am working on test writing procedure and policies.

**Comment by YuraYelisieiev** [comment]
@olemis done with test cover.

**Comment by YuraYelisieiev** [comment]
@olemis Give me pls feedback about the contribution guidelines. What's wrong with the first item in the checklist?

**Comment by jdknives** [comment]
I checked the last two ones because they looked good to me. Cannot evaluate the other checkmarks.

**Comment by olemis** [comment]
@YuraYelisieiev what's the PR ?

**Comment by jdknives** [comment]
https://github.com/skycoin/hardware-wallet/pull/201 @olemis

**Comment by YuraYelisieiev** [comment]
@olemis https://github.com/skycoin/hardware-wallet/pull/201

**Comment by jdknives** [comment]
Closed by #201
