### ISSUE TITLE
The recovery function is not working

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#169]
When calling the recovery function (`/recovery` in the daemon and `devRecoveryDevice` in the JS library) and confirming the operation, the device shows very briefly the word that must be written and immediately after that returns to the home screen. Because of this, it is not possible to see the word or continue with the operation.

**Environment information:**

- OS: Windows 10
- Platform: X64
- Firmware Version: 50000f6

**Steps to Reproduce**
Just call `/recovery` (with the daemon) or `devRecoveryDevice` (with the JS library).

**Actual behavior**
After confirming the operation, the device shows very briefly the word that must be written and immediately after that returns to the home screen.

**Expected behavior**
The word that must be written should be shown util the user enters it or cancels the operation.

**Additional context**
I tried doing the same with an old version of the firmware (compiled on March 18) and the problem was not present, the process worked correctly. This seems to indicate that the problem is due to a recently made change.

**Possible implementation**
None

**Comment by stdevStark** [comment]
> Just call `/recovery` (with the daemon) or `devRecoveryDevice` (with the JS library).

Maybe I solved it but for writing the tests , how to do it ? Like this is how I try it

- wallet connected
- it shows `needs seed`
- generate mnemonic
- it shows `need backup`
- recovery 

... but the value changes every time .

**Comment by stdevAlDen** [comment]
> > Just call `/recovery` (with the daemon) or `devRecoveryDevice` (with the JS library).
> 
> Maybe I solved it but for writing the tests , how to do it ? Like this is how I try it
> 
> * wallet connected
> * it shows `needs seed`
> * generate mnemonic
> * it shows `need backup`
> * recovery
> 
> ... but the value changes every time .

@stdevStark can you pls push you progress?

**Comment by Senyoret1** [comment]
> 
> 
> > Just call `/recovery` (with the daemon) or `devRecoveryDevice` (with the JS library).
> 
> Maybe I solved it but for writing the tests , how to do it ? Like this is how I try it
> 
>     * wallet connected
> 
>     * it shows `needs seed`
> 
>     * generate mnemonic
> 
>     * it shows `need backup`
> 
>     * recovery
> 
> 
> ... but the value changes every time .

The recovery procedure could be done in the third step (of after wiping the device) to recover a predefined seed. If that works, the problem I'm talking about is solved, but if you want to test a dry run with the recovery method, you can do it after recovering the predefined seed.

**Comment by olemis** [comment]
@stdevAlDen @stdevAlDen start it from scratch

**Comment by olemis** [comment]
> The recovery procedure could be done in the third step (of after wiping the device) to recover a predefined seed.

`setMnamonic` instead of `generateMnemonic`

**Comment by olemis** [comment]
6527b84

**Comment by Senyoret1** [comment]
This problem returned. I tested it with the firmware updated to 7aadfda , using the js library and the daemon.

**Comment by Senyoret1** [comment]
Tested with a wrong firmware version. Closing it again.
