### ISSUE TITLE
[Hardware Wallet]: Incorrect logo at startup

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#17]
Just after connecting the hardware wallet via USB, the Trezor logo is displayed for a brief moment and then is replaced by the Skycoin logo. That could cause problems in the future.

**Comment by mpsido** [comment]
need to change the logo in the bootloader

**Comment by mpsido** [comment]
quote from @Senyoret1
Today I updated the wallet using the bootloader and saw that when turning on the wallet with booth buttons pressed the Trezor logo is displayed. Maybe it should be removed

Also, after updating it says that I can unplug the "Skycoin W"

**Comment by mpsido** [comment]
I removed the skycoin logo from the bootloader because the smallest bitmap file i found for it is still too big for the bootloader memory. even when removing every other bitmap.

The text message csn be fixed. and about the logo I suggest "no logo" then.

**Comment by Senyoret1** [comment]
No logo may be good, as having the logo of another company may be problematic, but that is just my opinion. I can not make the decision.

**Comment by olemis** [comment]
What size is ok ?

**Comment by stdevAlDen** [comment]
> What size is ok ?

Let me check, with a data sheet and a hexdump could be possible determine the available size.

**Comment by olemis** [comment]
@stdevStark cpould you pls get this done asap ?

**Comment by stdevStark** [comment]
I have not device . I use the emulator . For this I need a device .

**Comment by olemis** [comment]
@stdevStark right ...

**Comment by olemis** [comment]
Fixed in 9f6aa3a
