### ISSUE TITLE
Fix info for features response in bootloader mode

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#187]
**Describe the bug**
A clear and concise description of the problem and bug effects.

**Environment information:**

- OS: e.g. Linux, Windows, Mac OS X
- Platform: the equivalent of `uname -smr` or `uname -smrv` e.g. Darwin 17.4.0 x86_64
- Firmware Version: e.g. 0.5.18

**Steps to Reproduce**

1. Plug the device in bootloader mode.
2. `go run cmd/cli/cli.go features`
3. Look at the response `{"vendor":"bitcointrezor.com","major_version":1,"minor_version":5,"patch_version":0,"bootloader_mode":true,"firmware_present":true}`

**Actual behavior**
Report **bitcointrezor.com** as vendor.

**Expected behavior**
Should report skycoin as vendor.

**Possible implementation**
Just look at the code:
https://github.com/skycoin/hardware-wallet/blob/7aadfda11ba350f2e67f421d3a5845065057b322/tiny-firmware/bootloader/usb.c#L245

Please be careful as the message is hardcoded in binary format, serialized.

**Comment by stdevAlDen** [comment]
> 3\. vendor

@gz-c what should be the value for `vendor` instead of `bitcointrezor.com`?

**Comment by olemis** [comment]
> @gz-c what should be the value for `vendor` instead of `bitcointrezor.com`?

skycoin.net ?

**Comment by stdevStark** [comment]
@stdevAlDen this is complete ?

**Comment by stdevAlDen** [comment]
> @stdevAlDen this is complete ?

@stdevStark yes https://github.com/skycoin/hardware-wallet/pull/200

**Comment by olemis** [comment]
fixed in 95f43f7
