### ISSUE TITLE
[Hardware Wallet]: The confirmation msg for locking device is too long

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#19]
The message that appears after pressing the left button of the wallet for a few moments, asking the users if they want to lock the wallet, is too long and does not fit on the screen.

**Comment by mpsido** [comment]
Do you have any proposition ?

**Comment by Senyoret1** [comment]
Probably just display "...want to lock your device?" or "...want to lock your wallet?" would fit. Using the current text and moving the part that does not fit to the third line could also work.
