### ISSUE TITLE
[Hardware Wallet]: The wallet “forgets” that it is necessary to make a backup

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#20]
The steps to reproduce the problem are:

- Connect a seedless hardware wallet.
- Assign a seed to the hardware wallet, either with `devGenerateMnemonic` or `devSetMnemonic`. After doing that the hardware wallet screen will display the “NEEDS BACKUP!” message.
- Disconnect the hardware wallet.
- Reconnect the hardware wallet. The hardware wallet screen will not display the “NEEDS BACKUP!” message.

The fact that the warning message disappears is, by itself, problematic. However, the problem is not just the message, but also that calling the `devBackupDevice` function of the `hardware-wallet-js` library returns an error, which seems to indicate that the hardware wallet reacts as if a backup were already been made and blocks any new attempt to make a backup, which in fact makes it impossible to backup the seed.

**Comment by mpsido** [comment]
Tien
>after your update, are those backup mnemonics supposed to show again if the previous try was interrupted halfway?
>Brandon
Its not done until its confirmed
