### ISSUE TITLE
Read UUID from physical device

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#202]
**Feature description**

Describe the feature
Read the full 96 bit unique identifier

**Is your feature request related to a problem? Please describe.**
Wanted [from here](https://github.com/skycoin/hardware-wallet/issues/141#issuecomment-476670129)

**Describe the solution you'd like**
Just read the manufacturer identifier.

**Comment by olemis** [comment]
fixed in b469846

**Comment by olemis** [comment]
remove `device_uuid` and always use `storage_uuid` .

**Comment by olemis** [comment]
remove `storage_generate_uuid` as well

**Comment by stdevAlDen** [comment]
> remove `storage_generate_uuid` as well

@olemis https://github.com/skycoin/hardware-wallet/pull/205/files#diff-995f347255144968a2480862f0b5cffbL772

**Comment by olemis** [comment]
fixed in e90f96b
