### ISSUE TITLE
Deployment keys

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#211]
**Feature description**

Add keys for Travis `deploy`

**Is your feature request related to a problem? Please describe.**
Auth failure during Travis deploy since keys not generated for upstream repository

**Describe the solution you'd like**
Secure keys in Travis script for deployment tokens (see details below)

**Additional context**
#210 and #183 create in spite of writing code to release artifacts that need to be signed 

**Possible implementation**

- ~Add secure key for Github Releases~
- [ ] Remove deployment to Github Releases
- [x] Add secure key for S3 deployment (see [the original patch](https://github.com/skycoin/hardware-wallet/pull/214/files#diff-354f30a63fb0907d4ad57269548329e3R85) )

**Comment by stdevAlDen** [comment]
> **Feature description**
> 
> Add keys for Travis `deploy`
> 
> **Is your feature request related to a problem? Please describe.**
> Auth failure during Travis deploy since keys not generated for upstream repository
> 
> **Describe the solution you'd like**
> Secure keys in Travis script for deployment tokens (see details below)
> 
> **Additional context**
> #210 and #183 create in spite of writing code to release artifacts that need to be signed
> 
> **Possible implementation**
> 
> * [ ]  Add secure key for Github Releases
> * [ ]  Add secure key for S3 deployment

https://github.com/skycoin/hardware-wallet/pull/214#issuecomment-489680610

**Comment by gz-c** [comment]
Setup s3 keys in travis

**Comment by stdevAlDen** [comment]
> Setup s3 keys in travis

excuse me @gz-c  did you set up a suitable key for the github releases too?
- https://github.com/skycoin/hardware-wallet/blob/ffd6fcdaf1d89a0877372f6549cd8a4035a49760/.travis.yml#L63
 - https://github.com/skycoin/hardware-wallet/blob/ffd6fcdaf1d89a0877372f6549cd8a4035a49760/.travis.yml#L76

**Comment by gz-c** [comment]
I set the `AWS_ACCESS_KEY_ID`, `AWS_BUCKET`, `AWS_REGION` and `AWS_SECRET_ACCESS_KEY` variables in travis.  I did not use travis.yml's encrypted `secure` field.  Refer to github.com/skycoin/skycoin for the way we use these keys to upload the artifacts

**Comment by olemis** [comment]
> I set the `AWS_ACCESS_KEY_ID`, `AWS_BUCKET`, `AWS_REGION` and `AWS_SECRET_ACCESS_KEY` variables in travis

@gz-c thanks . Nonetheless it seems Github Releases token still missing . Could you please add it ? Can't do it myself .
