### ISSUE TITLE
A posible error not handled in `SignMessage`

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#217]
**Describe the bug**
In [`fsm_msgSkycoinSignMessage`](https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm.c#L339) some possible errors are currently ignored from [`fsm_getKeyPairAtIndex`](https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm.c#L347) call.

**Environment information:**

- Any

**Steps to Reproduce**
A code review

**Actual behavior**
Wrong implementation

**Expected behavior**
Just fix the bug handling the posible errors.

**Additional context**
None

**Comment by olemis** [comment]
fixed in 6117a70
