### ISSUE TITLE
Bug in fsm_msgSkycoinCheckMessageSignature

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#219]
**Describe the bug**
When calling [`msgSkycoinCheckMessageSignatureImpl`](https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm.c#L297) the user should see some relevant info in the screen according to this code:
https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm_impl.c#L228-L231

But this message will be overwritten immediately by a [`layoutHome`](https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm.c#L303) call

**Environment information:**

Any

**Steps to Reproduce**
Just follow the logic in source code.

**Actual behavior**
the layout home override the previos info in the screen

**Expected behavior**
TODO @olemis & @therealssj please help me to define the desired behavior

**Additional context**
None

**Possible implementation**
TODO

**Comment by therealssj** [comment]
I don't think the user needs to see an error message here. 
The function should just return an error message and the desktop wallet should display an error accordingly

**Comment by olemis** [comment]
fixed by 0268088
