### ISSUE TITLE
Bug in fsm_msgSkycoinSignMessage protocol message sequence

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#220]
**Describe the bug**
At calling [`msgSkycoinSignMessageImpl`](https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm.c#L353) the [client receive a response from here](https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm_impl.c#L129) and then a second one it's sended [from here](https://github.com/skycoin/hardware-wallet/blob/2ffb2af49c8100dbca6645e8ff9847f1544cf3ba/tiny-firmware/firmware/fsm.c#L358).

**Environment information:**

Any

**Steps to Reproduce**
Just look at the ource code in avobe comment

**Actual behavior**
Sending two responses.

**Expected behavior**
It's required to send just one response

**Comment by olemis** [comment]
fixed in 7bcbdcb
