### ISSUE TITLE
Create instructions for bootloader flashing

### ISSUE THREAD

**Issue by jdknives** [skycoin/hardware-wallet#233]
**Feature description**

We need a concise and simple description for how to flash the bootloader onto a board WITHOUT flashing the firmware on it. It should describe: 

- [x] what devices are required

- [x] how to connect them

- [x] what software needs to be running

- [x] Step by Step instruction to flash the bootloader in Mem_protect mode AND in development mode

- [x] what to look for to see whether the bootloader was flashed

**Is your feature request related to a problem? Please describe.**
We need the hardware office to be able to flash the bootloader only to do a dry run before prodcution.

**Comment by olemis** [comment]
ready
