### ISSUE TITLE
Empty passphase in Recovery message leads to generating wrong addresses

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#243]
**Describe the bug**
Setting `usePassphase` in Recovery message leads to generating wrong addresses

**Environment information:**

- OS: Mac OS X
- Platform: Darwin 17.4.0 x86_64
- Firmware Version: 46ef0d346a835263d0c060d074652698954613f7

**Steps to Reproduce**

- Create new wallet e.g. with `skycoin-cli`
```sh
skycoin-cli walletCreate -f $WALLET1.wlt -l $WALLET1
```
- From command output take note of the seed `SEED1` and address `ADDRESS1`
- List wallet addresses and confirm that `ADDRESS1` is the only value in the list.
```sh
skycoin-cli listAddresses $WALLET1.wlt
```
- Ensure device is seedless by [wiping it](https://github.com/skycoin/hardware-wallet-js/tree/master/DOCUMENTATION.md#devWipeDevice). Check that you end up in home screen with `NEEDS SEED!` message at the top.
- [Recover seed](https://github.com/skycoin/hardware-wallet-js/tree/master/DOCUMENTATION.md#devRecoveryDevice) `SEED1` in Skywallet device (`dry-run=false`, `usePassphrase=true`).
  * Enter empty passphrase when requested
- [Generate five addresses using Skywallet](https://github.com/skycoin/hardware-wallet-js/tree/master/DOCUMENTATION.md#devAddressGen)
- Check that address sequence generated by SkyWallet matches the values generated by `skycoin-cli`
```sh
skycoin-cli walletAddAddresses -f $WALLET1.wlt -n 5
```

**Actual behavior**
Skywallet addresses ...

```
26MgaacLTydj2tgcgR1SCAMuDLMvstXwUGG
27SVD1r3Jbb238C2VmHQsdPiTCp7dZN2Ryp
UCo7rQ2vJZTYdRpmebxx44KrVyixnKekuW
2dyk9NuqoWY5L1yLQxqPGn1uoHRmvFmvfbd
2P1mjpJSrbttKt4F6AuX9Vfh48zZYfSyjZf
```

... do not match `skycoin-cli` output

```
Mh9jEhCi23WqSD1SmbJz5PGBArHviHcC2a
eKyAeTqsK3x2Pj1gcSfUzogMRfz85JASzU
2Ene7utsDjhhBuHnBtU15cuUKWpadUkTUDr
7FiHj1ayVBTAfszMDGnV1WCriDMHmT9PAZ
VMsZnKjP6vQQtfUiWRJdCFFSHyoR4H6wSK
```

**Expected behavior**
Provided same seed is recovered on both wallets , Skywallet address sequence must match values generated by `skycoin-cli` provided that passphrase is empty.

**Additional context**
Discovered while following hw-js pre-release testing procedure skycoin/hardware-wallet-js#112

**Comment by olemis** [comment]
Expected behavior . For v1 `passphrase` must always be `false` .

**Comment by olemis** [comment]
Nonetheless this should be more visible in dev and user docs .

**Comment by stdevAlDen** [comment]
the good news are that the [libskycoin tests](https://github.com/skycoin/hardware-wallet/pull/232) are failing about this, but need to look for more details

**Comment by jdknives** [comment]
@olemis if this is expected behavior for v1, why is the Milestone 1 attached? What is to be done about this for v1?

**Comment by olemis** [comment]
> What is to be done about this for v1?

Ensure that if `usePassphrase=true` and `passphrase=''` then behavior is the same as `usePassphrase=false` .
