### ISSUE TITLE
Label erased after device recovery

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#244]
**Describe the bug**
Label erased after device recovery

**Environment information:**

- OS: Mac OS X
- Platform: Darwin 17.4.0 x86_64
- Firmware Version: 46ef0d3

**Steps to Reproduce**

1. Checkout 46ef0d3
2. Run `make clean && make firmware`
3. Flash it onto device e.g. hw-go `firmwareUpdate`
4. Check skycoin/hardware-wallet-js@7c8befc635378a985deeb20b34fdb65f03344bc4
5. Run `node ci-scripts/pre-release.features.js`
6. Run `node ci-scripts/pre-release.recovery.js` and follow recovery procedure for a given wallet seed (exact value does not matter as long as it's a valid mnemonic)
7. Run `node ci-scripts/pre-release.features.js` once again

**Actual behavior**
First time `GetFeatures` is executed this is the result

```
Features {
  vendor: 'Skycoin Foundation',
  deviceId: '35383935065137331B003B00',
  pinProtection: false,
  passphraseProtection: false,
  label: '35383935065137331B003B00',
  initialized: false,
  bootloaderHash:
   Uint8Array [
     176,
     116,
     162,
     71,
     92,
     25,
     181,
     200,
     192,
     109,
     12,
     66,
     210,
     204,
     118,
     222,
     11,
     154,
     16,
     92,
     202,
     210,
     48,
     15,
     50,
     204,
     235,
     97,
     198,
     198,
     245,
     104 ],
  pinCached: false,
  passphraseCached: false,
  needsBackup: false,
  model: '1',
  fwMajor: 1,
  fwMinor: 7,
  fwPatch: 0,
  firmwareFeatures: 0 }
```

Second time it returns the following values . Notice that `label` is missing (i.e. empty).

```
Features {
  vendor: 'Skycoin Foundation',
  deviceId: '35383935065137331B003B00',
  pinProtection: false,
  passphraseProtection: false,
  initialized: true,
  bootloaderHash:
   Uint8Array [
     176,
     116,
     162,
     71,
     92,
     25,
     181,
     200,
     192,
     109,
     12,
     66,
     210,
     204,
     118,
     222,
     11,
     154,
     16,
     92,
     202,
     210,
     48,
     15,
     50,
     204,
     235,
     97,
     198,
     198,
     245,
     104 ],
  pinCached: false,
  passphraseCached: false,
  needsBackup: false,
  model: '1',
  fwMajor: 1,
  fwMinor: 7,
  fwPatch: 0,
  firmwareFeatures: 0 }
```

**Expected behavior**
Device label should not be modified after recovery .

**Additional context**
Detected during hw-js pre-release testing (see skycoin/hardware-wallet-js#112)

**Comment by Retsediv** [comment]
Does this bug appear only for hw-js wrapper? Do you have the same functionality for hw-go wrapper (i mean `pre-release.features` and `pre-release.recovery`)?

**Comment by olemis** [comment]
> Does this bug appear only for hw-js wrapper?

hw-js , hw-go , and hw-daemon

> Do you have the same functionality for hw-go wrapper (i mean `pre-release.features` and `pre-release.recovery`)?

no

**Comment by olemis** [comment]
> > Do you have the same functionality for hw-go wrapper (i mean `pre-release.features` and `pre-release.recovery`)?
> 
> no

Indeed, I reviewed hw-go pre-release once again and some things need to be fixed

**Comment by Retsediv** [comment]
@olemis I have just tried to reproduce this feature (on Linux with the same version of firmware and hardware-wallet-js) and it does not appear
Do you have some thought on that?

**Comment by jdknives** [comment]
@Retsediv can someone on Mac check whether they can reproduce the issue?

**Comment by Macrosrider** [comment]
@olemis The same issue was reproduced on Windows (with the same version of firmware and hardware-wallet-js). So, this is not only Mac OS issue

**Comment by olemis** [comment]
> @olemis The same issue was reproduced on Windows (with the same version of firmware and hardware-wallet-js). So, this is not only Mac OS issue

Cool ! Thanks ... @Retsediv any progress ?

**Comment by Retsediv** [comment]
> > @olemis The same issue was reproduced on Windows (with the same version of firmware and hardware-wallet-js). So, this is not only Mac OS issue
> 
> Cool ! Thanks ... @Retsediv any progress ?

So far, I could not reproduce it on Linux(and I do not have any other OS). Although, now I have installed a new Linux distro and will recheck everything. Will let you know soon

**Comment by Retsediv** [comment]
@olemis unfortunately, I still can not reproduce this bug on Linux

@YuraYelisieiev can you take this issue?

**Comment by YuraYelisieiev** [comment]
@Retsediv will finish with my issues and take a look at this one.

**Comment by olemis** [comment]
> @Retsediv will finish with my issues and take a look at this one.

@stdevStark will take it fom here .
