### ISSUE TITLE
Unused values in recover_pubkey_from_signed_message

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#249]
**Describe the bug**
Some variables are unused after initialization.

**Environment information:**

- OS: Any
- Platform: Any
- Firmware Version: 46ef0d346a835263d0c060d074652698954613f7

**Steps to Reproduce**

Look at https://github.com/skycoin/hardware-wallet/blob/46ef0d346a835263d0c060d074652698954613f7/skycoin-api/skycoin_check_signature.c#L96

**Actual behavior**
After putting some values in [`r` and `s`](https://github.com/skycoin/hardware-wallet/blob/46ef0d346a835263d0c060d074652698954613f7/skycoin-api/skycoin_check_signature.c#L97-L98) these are not used.

**Expected behavior**
Maybe these values should be used.

PD: Maybe there is not a bug at all but it's recommended to get a review from a crypto-expert

**Comment by jdknives** [comment]
@stdevAlDen asked @gz-c for his opinion.
