### ISSUE TITLE
Make verify_digest_recover conform to secp256k1.RecoverPubkey

### ISSUE THREAD

**Issue by jdknives** [skycoin/hardware-wallet#256]
**Describe the bug**
During @gz-c review of  the crypto files, it was discovered, that `verify_digest_recover`, does not conform to `secp256k1.RecoverPubkey` in skycoin/skycoin. The tests pass, but there may be edge cases that are unaccounted for. 

**Possible implementation**
Transpile the function to make it conform to `secp256k1.RecoverPubkey`.

**Comment by gz-c** [comment]
Fixed by #254
