### ISSUE TITLE
test_signature only checks the first 32 bytes of the signature

### ISSUE THREAD

**Issue by gz-c** [skycoin/hardware-wallet#262]
The tests in `test_signature` only check the first 32 bytes of the signature.  If there is a reason for that, it should be explained why, otherwise the full signature should be checked, and it should match the result of the skycoin core libs.

**Comment by olemis** [comment]
https://github.com/skycoin/hardware-wallet/blob/develop/skycoin-api/test_skycoin_crypto.c#L377-L378

@gz-c 32 + 32 = 64

**Comment by olemis** [comment]
> https://github.com/skycoin/hardware-wallet/blob/aabc77d/skycoin-api/test_skycoin_crypto.c#L377-L378
> 
> @gz-c 32 + 32 = 64

**Comment by gz-c** [comment]
I see; this will be fixed in my PR

**Comment by olemis** [comment]
Testing for this will be ported from `skycoin/libskycoin` as part of work done for #232

**Comment by olemis** [comment]
> it should match the result of the skycoin core libs.

this is thge specific part that will be added in #232

**Comment by gz-c** [comment]
The fix was to remove those tests because the funciton it tested was removed.  Then to port those tests to the new function. There isn't a bug, the 32 is the 32 bytes of the R,S points of the signature. The bug was that it wasn't checking the recovery ID.  

This problem is resolve by my PR.
