### ISSUE TITLE
Bootloader signature test

### ISSUE THREAD

**Issue by gz-c** [skycoin/hardware-wallet#270]
**Feature description**

Have an automated test for the bootloader signing.  It should compile the bootloader, sign it, then validate the signatures. 

Since the pubkeys are hardcoded, and associated with production secret keys, we'll need a mechanism to swap the pubkeys in the bootloader to some temporarily generated keys for the test.

**Comment by stdevAlDen** [comment]
@gz-c | @jdknives | @olemis 
Scenario:
 - From [here](https://github.com/simelo/skycoin-hardware-wallet/blob/14e0227c16faad2ba39280bb6dc794c0821d761c/Makefile#L209) I'm signing a firmware.
 - From [here](https://github.com/simelo/skycoin-hardware-wallet/blob/14e0227c16faad2ba39280bb6dc794c0821d761c/Makefile#L210) I'm checking that the signature is ok.

Problem:
 - I have no set any `FIRMWARE_SIGNATURE_SEC_KEY` (look at [the end of the line](https://github.com/simelo/skycoin-hardware-wallet/blob/14e0227c16faad2ba39280bb6dc794c0821d761c/Makefile#L209)).

Question:
 - Can I put a dummy(used only for the test purpose, nothing else) private key in plan text as part of the code?
