### ISSUE TITLE
Programatically press emulator buttons

### ISSUE THREAD

**Issue by mpsido** [skycoin/hardware-wallet#28]
This feature could be very useful to create automatic tests.

The automatic tests could be inserted in travis build to increase robustness

**Comment by mpsido** [comment]
important files to start hacking:
emulator/udp.c
emulator/buttons.c

**Comment by mpsido** [comment]
Even if I do create this possibility some actions like input pincode or recovery seed need an user reading what is written on the screen

**Comment by Dawn-Piper** [comment]
we will add this at a later stage

**Comment by olemis** [comment]
@stdevHan pls try this https://stackoverflow.com/questions/35760351/simulate-keyboard-button-press-sdl-library . If not possible to do it from a remote process then implement a web server in emulator SDL app and listen for test commands . One such command should be pressing a button (given its GUI component ID).

**Comment by olemis** [comment]
@stdevIvr what's the progress on this ? This is blocking other issues e.g. skycoin/skycoin#1783 , skycoin/hardware-wallet-js#59 (see [build failure](https://travis-ci.com/skycoin/hardware-wallet-js/builds/101709851) for skycoin/hardware-wallet-js#62) .

**Comment by stdevIvr** [comment]
I'm trying to trigger the button event but I haven't yet. What I did was to add a middleware in the emulator in order to intercept specific messages to press the button. That works, but the button isn't really pressed yet. Still working on that.

**Comment by olemis** [comment]
fixed by 9a86d9b
