### ISSUE TITLE
[Hardware-Wallet]: Ask PINCODE to allow wipe device and "set mnemonic"

### ISSUE THREAD

**Issue by mpsido** [skycoin/hardware-wallet#29]
Device wipe erases everything including pin code and mnemonic. If the user protected his device with a pin code it makes sense to ask for pin code before wiping everything.

**Comment by Senyoret1** [comment]
The problem with this is that if the user forgets his PIN, then the hw would be totally unusable. If it is allowed to wipe the hw without the PIN, the user could just wipe and restore it with the seed.

**Comment by mpsido** [comment]
good point @Senyoret1
