### ISSUE TITLE
Verify code coverage setup in OS X

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#302]
**Feature description**

Describe the feature

**Is your feature request related to a problem? Please describe.**
Just check that the [code coverage report](https://github.com/simelo/skycoin-hardware-wallet/tree/adeaaa695caeea8f35a86d212714bf31d76f9ef3#generating-tests-code-coverage) works as expected in osx

**Possible implementation**

Follow [the instructions](https://github.com/simelo/skycoin-hardware-wallet/tree/adeaaa695caeea8f35a86d212714bf31d76f9ef3#generating-tests-code-coverage).

**Comment by YuraYelisieiev** [comment]
@stdevAlDen @olemis doesn`t work for OSX.

**Comment by stdevAlDen** [comment]
@YuraYelisieiev did you install the [required tools](https://github.com/skycoin/hardware-wallet#generating-tests-code-coverage)?
what error are you having?

**Comment by YuraYelisieiev** [comment]
> @YuraYelisieiev did you install the [required tools](https://github.com/skycoin/hardware-wallet#generating-tests-code-coverage)?
> what error are you having?

@stdevAlDen yeap, I followed the instructions, but I have this error. 
```make
Undefined symbols for architecture x86_64:
  "_llvm_gcda_emit_arcs", referenced from:
      ___llvm_gcov_writeout in test_skycoin_crypto.o```

**Comment by YuraYelisieiev** [comment]
@stdevAlDen  review last comment please.

**Comment by YuraYelisieiev** [comment]
skycoin-api is a library so we can`t test it using clang.
