### ISSUE TITLE
[Hardware-Wallet]: create a device label

### ISSUE THREAD

**Issue by mpsido** [skycoin/hardware-wallet#32]
Device Label is a "name" that can appear on the screen and be used to identify a device.

Supporting this feature now is not complicated but requires a bunch of extra specifications like:
* shall we create a specific message to label the device ?
* how do we display it on the screen ?

**Comment by vtatischev** [comment]
Can we use "Skycoin" + UUID? Or similar string because in my opinion any HW has ID number

**Comment by vtatischev** [comment]
For displaying this string we can add function in JS API and/or implement small program for systray

**Comment by olemis** [comment]
completed in 230a1d5
