### ISSUE TITLE
Openocd support

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#329]
**Feature description**

Confirm if we are going to support openocd
https://github.com/skycoin/hardware-wallet/blob/d43657c574dad5ed5c823a32f30b04e94fd6f356/Makefile#L229-L230

if "yes", then check if this is working properly.

**Describe the solution you'd like**
Work based on the decision.

**Comment by Macrosrider** [comment]
@stdevAlDen where is openocd.cfg file?

**Comment by Macrosrider** [comment]
@stdevAlDen, I wrote a simple *.cfg file, which flash firmware to the hw (more info here bdba94f). "make oflash" command works perfect on Linux and Windows. Can someone check it on MacOS?

**Comment by stdevStark** [comment]
> Can someone check it on MacOS?

I can take a look

**Comment by stdevStark** [comment]
> I wrote a simple *.cfg file, which flash firmware to the hw (more info here [525d9a5](https://github.com/skycoin/hardware-wallet/commit/525d9a5b9a47bf9e41baafe3da5f74817642b897)).

could you please add a new PR ?

**Comment by Macrosrider** [comment]
@stdevStark , will do it in a few minutes

**Comment by stdevStark** [comment]
> more info here [525d9a5](https://github.com/skycoin/hardware-wallet/commit/525d9a5b9a47bf9e41baafe3da5f74817642b897)

@Macrosrider how can I `git fetch` those changes ? what fork is yours ?

**Comment by Macrosrider** [comment]
@stdevStark, please check related PR. Suddenly, it failed on Travis and I have no idea why, because I've just fetch upstream of skycoin/develop

**Comment by stdevAlDen** [comment]
> @stdevStark, please check related PR. Suddenly, it failed on Travis and I have no idea why, because I've just fetch upstream of skycoin/develop

@Macrosrider due to an update in the ubuntu repository, should be get solved after merging [this pr](https://github.com/skycoin/hardware-wallet/pull/333)
@olemis | @jdknives apply for [this](https://github.com/skycoin/hardware-wallet/pull/334) and all incoming pr, so please review -> merge asap.
