### ISSUE TITLE
[Hardware-Wallet]: Reshape Recovery seed for skycoin needs

### ISSUE THREAD

**Issue by mpsido** [skycoin/hardware-wallet#33]
Here is the currently existing RecoveryDevice structure:

```
message RecoveryDevice {
	optional uint32 word_count = 1;				// number of words in BIP-39 mnemonic
	optional bool passphrase_protection = 2;		// enable master node encryption using passphrase
	optional bool pin_protection = 3;			// enable PIN protection
	optional string language = 4 [default='english'];	// device language
	optional string label = 5;				// device label
	optional bool enforce_wordlist = 6;			// enforce BIP-39 wordlist during the process
	// 7 reserved for unused recovery method
	optional uint32 type = 8;				// supported recovery type (see RecoveryType)
	optional bool dry_run = 10;				// perform dry-run recovery workflow (for safe mnemonic validation)
}
```

We won't use the following elements: `dry_run` `type`, `enforce_wordlist` 

We don't use these yet:
* `word_count`: (fixed to value 12) 
* `language`: #26 
* `label`: #32

An **extra attention** need to be given to : `passphrase_protection` `pin_protection` (shall we unable configuration of these things from this message) ?

**Comment by mpsido** [comment]
Related to #27

**Comment by mpsido** [comment]
Related to https://github.com/skycoin/hardware-wallet-js/issues/31

**Comment by olemis** [comment]
in the desktop wallet 12 or 24
<img width="570" alt="screen shot 2019-01-30 at 2 23 02 pm" src="https://user-images.githubusercontent.com/538253/52006625-9da65d00-249a-11e9-89cd-0e97a236344e.png">

**Comment by olemis** [comment]
@stdevAlDen in Trezor code 12, 18, 24
https://github.com/skycoin/hardware-wallet/blob/master/skycoin-api/trezor-tools/bip39.c#L142

**Comment by olemis** [comment]
closed by 801806e

**Comment by olemis** [comment]
@stdevAlDen [new issues](https://github.com/skycoin/skycoin/issues/2165#issuecomment-463348983) found .

**Comment by olemis** [comment]
[False alarm](https://github.com/skycoin/skycoin/issues/2165#issuecomment-464921548). Closing this issue once again .
