### ISSUE TITLE
[Hardware-Wallet]: Make a guide for firmware upgrade release

### ISSUE THREAD

**Issue by TienZhao** [skycoin/hardware-wallet#34]
We want to have a step-by-step guide for releasing firmware upgrade versions. The guide is supposed to start from listing all the resources needed, and ends at having a file that everybody can download for upgrade.

**Comment by mpsido** [comment]
I am still wondering what you want in it. All the steps are described in the tiny-firmware/README.md file.
So I believe it is too complicated for non developer. But if so someone has to do the compilation anyway.

I was considering creating a docker file doing the compilation for you. but to use it you need to have docker installed and be able to run it.

**Comment by mpsido** [comment]
Process to update firmware for users: https://wiki.trezor.io/index.php?title=User+manual%3AUpdating+the+Trezor+device+firmware&ModelType=1

**Comment by mpsido** [comment]
Once issue #50 is solve this issue will be deprecated.
To create a release it will be just : `make release` command
