### ISSUE TITLE
Deterministic Builds

### ISSUE THREAD

**Issue by Midren** [skycoin/hardware-wallet#36]
@mpsido commented on Dec 26, 2018
It seems that "Gitian" allows creating deterministic builds in order to make sure the executable we use is really compiled from the source code we have.

I found a gitian.yml configuration file in trezor repository.

Here is a presentation of gitian:
https://bitcoinmagazine.com/articles/what-is-gitian-building-how-bitcoin-s-security-processes-became-a-model-for-the-open-source-community-1461862937/

**Comment by Midren** [comment]
@mpsido  commented on Dec 26, 2018 
Question is : shall I spend time on this ?

**Comment by Midren** [comment]
@mpsido commented on Dec 26, 2018
see also https://blog.torproject.org/deterministic-builds-part-two-technical-details

**Comment by Midren** [comment]
@mpsido commented on Dec 26, 2018
try this: https://stackoverflow.com/questions/14653874/how-to-produce-deterministic-binary-output-with-g

**Comment by RomanMilishchuk** [comment]
@mpsido commented on Dec 26, 2018
try this: https://stackoverflow.com/questions/14653874/how-to-produce-deterministic-binary-output-with-g

**Comment by Midren** [comment]
@mpsido commented on Dec 26, 2018
Could get a deterministic emulator build by adding the compilation flag CFLAGS += -frandom-seed=123

Not tested on cross compiler

**Comment by Midren** [comment]
@mpsido commented on Jan 11, 2019
Two consecutive build on the same machine have the same hash after commit [`0598635`](https://github.com/skycoin/hardware-wallet/commit/059863567898a6d51cd7b3a89dac8b32e1dc8f80)
But the md5sum was different on travis and on my machine

My machine:
> md5sum tiny-firmware/bootloader/combine/*.bin
> 80ba69a16c4505b5cefd5c57b2079988  tiny-firmware/bootloader/combine/bl.bin
> 45392d6448393628ad2d3c961555f758  tiny-firmware/bootloader/combine/combined.bin
> 6665e97131e7d4d84f2dfa184d53d10b  tiny-firmware/bootloader/combine/fw.bin

On [travis build 77](https://travis-ci.com/skycoin/hardware-wallet/builds/97003523)
> md5sum tiny-firmware/bootloader/combine/*.bin
> 094d87060c2143d5607260aa5cb710c2  tiny-firmware/bootloader/combine/bl.bin
> 1cc13e8025bdd2a859d92bd30dfdc666  tiny-firmware/bootloader/combine/combined.bin
> e9c3b403735363060db06fc3a897a048  tiny-firmware/bootloader/combine/fw.bin

**Comment by jdknives** [comment]
@RomanMilishchuk please outline the plan you have come up for implementing this.

**Comment by Midren** [comment]
Nondeterministic builds are because of:
- A different version of the compiler
- Timestamp in binaries
- Info about the directory in binary
- Different order of same object files, which are inserted in libraries
- Nondeterminism created by the compiler with enabled Link-Time Optimizations (-flto flag)

To solve all of them I propose next solutions:
- Use Docker to always have the same compiler and OS (It will also help to compile hw on the new OS)
- use environment variable SOURCE_DATE_EPOCH
- flag -fdebug-prefix-map=OLD=NEW will delete info about directory
- In the makefile, we are using wildcards *, but bash [guarantees](https://serverfault.com/questions/122737/in-bash-are-wildcard-expansions-guaranteed-to-be-in-order), that they will be in alphabetical order
- For each source file, we should give a unique value to flag -frandom-seed
