### ISSUE TITLE
Add legacy Bitcoin adresses generation

### ISSUE THREAD

**Issue by Midren** [skycoin/hardware-wallet#45]
Add Bitcoin addresses generation.
 
**Describe the solution you'd like**
Add keypair iterating through Bitcoin public/private keys. Also, add function to make Bitcoin addresses from public key and function to get the address from hardware-wallet using hardware-wallet-go CLI.

**Additional context:**
Message for getting address should be written in a files fsm_bitcoin and fsm_bitcoin_impl.

As we don't support BIP32/44, so Skycoin's keypair generation function should be adopted to be used for other coins. For example, deterministic_key_pair_iterator_step produces [skycoin pubkey](https://github.com/SkycoinProject/hardware-wallet/blob/545517c0c766c54baaca19c0fdf057b6c46b2393/skycoin-api/skycoin_crypto.c#L127), so it cannot be used for Bitcoin.

**Possible solution:**
Make deterministic_key_pair_iterator more abstract and add one parameter, which will be the pointer to the function, which generates pubkey from seckey. Then make deterministic_<coin_name>_key_pair_iterator functions, which will be calling deterministic_key_pair_iterator with specific function.

- [x] Adapt Skycoin's keypair iteration function to be used for other coins.
- [x] Add message function with protobuff, so the address can be getting from CLI.
- [x] Add tests for it

**Comment by jdknives** [comment]
Closed by #47
