### ISSUE TITLE
Create a firmware version deployment usable from Makefile

### ISSUE THREAD

**Issue by mpsido** [skycoin/hardware-wallet#50]
Add a rule on the main Makefile allowing to pass a Version number, the firmware should be built and named accordingly

**Comment by stdevAlDen** [comment]
@mpsido what do you think about making this part of a CI/CD process?

**Comment by olemis** [comment]
In my opinion the whole feature should be:

- [ ] `make release` target
- [ ] get version from Github tag, for other cases set it to (short?) SHA1 of the git commit 
- [ ] display version in hardware wallet UI
- [ ] transmit software version (e.g. for software update notifications in desktop wallet)

**Comment by olemis** [comment]
having a version number tuple plus commit hash should be ok too

**Comment by mpsido** [comment]
The PR #51 should be closing this issue. If not, please say what is missing to it

**Comment by stdevAlDen** [comment]
> In my opinion the whole feature should be:
> 
>     * [ ]  `make release` target
> 
>     * [ ]  get version from `git` tag, for other cases set it to (short?) SHA1 of the git commit
> 
>     * [ ]  display version in hardware wallet UI
> 
>     * [ ]  transmit software version (e.g. for software update notifications in desktop wallet)

In addition:
* [ ] remove hard coded version from [firmware](https://github.com/skycoin/hardware-wallet/blob/92cfdf850174a6abbf55bb49af84f3f7c1926b4b/tiny-firmware/firmware/trezor.h#L25-L36) and [bootloader](https://github.com/skycoin/hardware-wallet/blob/92cfdf850174a6abbf55bb49af84f3f7c1926b4b/tiny-firmware/bootloader/bootloader.h#L23-L38).
* [ ] To be able to get a version from CI/CD automatically, consider split this repository in two, bootloader and firmware, maybe 3 with the common source code between [firmware](https://github.com/skycoin/hardware-wallet/blob/92cfdf850174a6abbf55bb49af84f3f7c1926b4b/tiny-firmware/Makefile#L16-L19) and [bootloader](https://github.com/skycoin/hardware-wallet/blob/92cfdf850174a6abbf55bb49af84f3f7c1926b4b/tiny-firmware/bootloader/Makefile#L6-L9) for example.
* [ ] Use `VERSION_BOOTLOADER_` [here](https://github.com/skycoin/hardware-wallet/blob/92cfdf850174a6abbf55bb49af84f3f7c1926b4b/Makefile#L83).
* [ ] Check out how to do [this](https://github.com/skycoin/hardware-wallet/blob/92cfdf850174a6abbf55bb49af84f3f7c1926b4b/Makefile#L83).
* [ ] Check out [this](https://github.com/skycoin/hardware-wallet/blob/92cfdf850174a6abbf55bb49af84f3f7c1926b4b/Makefile#L15-L22).

Related to:

- https://github.com/skycoin/hardware-wallet/issues/46
- https://github.com/skycoin/hardware-wallet/issues/64
- https://github.com/skycoin/hardware-wallet/issues/98

@therealssj & @olemis

**Comment by olemis** [comment]
fixed in 5860c3e
