### ISSUE TITLE
[QUESTION] Problem to get stlink working on linux with hardware device.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#52]
**Kernel log:**

```
[12327.893260] usb 2-9: new full-speed USB device number 18 using xhci_hcd
[12328.025292] usb 2-9: device descriptor read/64, error -71
[12328.261298] usb 2-9: device descriptor read/64, error -71
[12328.497234] usb 2-9: new full-speed USB device number 19 using xhci_hcd
[12328.625318] usb 2-9: device descriptor read/64, error -71
[12328.861267] usb 2-9: device descriptor read/64, error -71
[12328.969319] usb usb2-port9: attempt power cycle
[12329.621238] usb 2-9: new full-speed USB device number 20 using xhci_hcd
[12329.621361] usb 2-9: Device not responding to setup address.
[12329.829371] usb 2-9: Device not responding to setup address.
[12330.037234] usb 2-9: device not accepting address 20, error -71
[12330.169296] usb 2-9: new full-speed USB device number 21 using xhci_hcd
[12330.169417] usb 2-9: Device not responding to setup address.
[12330.377373] usb 2-9: Device not responding to setup address.
[12330.585276] usb 2-9: device not accepting address 21, error -71
[12330.585361] usb usb2-port9: unable to enumerate USB device
```

**My Host (checked in an Ubuntu machine too and get the same error):**
Linux hostname 4.19.0-1-amd64 1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux

**Device connection**:
![device](https://user-images.githubusercontent.com/34870496/51359477-ecfd8e00-1a95-11e9-9e8e-9feeb3ac47dd.jpg)

Some one can help me to solve this issue?

@mpsido  can you pls help me to label this issue as question? I do not have permission.

**Comment by mpsido** [comment]
@stdevAlDen   did you do [this configuration](https://github.com/skycoin/hardware-wallet/tree/master/tiny-firmware#configure-your-usb-module)

**Comment by stdevAlDen** [comment]
@mpsido yes, even restarting the system in addition to `udev` reload rules

**Comment by mpsido** [comment]
@stdevAlDen I can't tell much with the information I have right here:
Here is what I recommend to check:

## Double check the configuration
```
cat /etc/udev/rules.d/*
```
Check that somewhere in your rules the following appears:
```
## 0483:df11 STMicroelectronics STM Device in DFU Mode
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="df11", MODE="0666"
## 0483:3748 STMicroelectronics ST-LINK/V2
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="3748", MODE="0666"
## 0483:374b STMicroelectronics ST-LINK/V2.1 (Nucleo-F103RB)
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="374b", MODE="0666"
## 313a:0001
SUBSYSTEM=="usb", ATTR{idVendor}=="313a", ATTR{idProduct}=="0001", MODE="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="313a", ATTRS{idProduct}=="0001", MODE="0666"
EOF
```
## Skip the wrong firmware warning

Check also [this section](https://github.com/skycoin/hardware-wallet/tree/master/tiny-firmware#skip-the-wrong-firmware-signature-warning) of the README.md file.

If you have the wrong firmware signature warning and don't skip it soon enough (less than 3 seconds), the OS gives up on trying to talk with the device

## My dmesg log:

```
[ 6367.667600] usb 1-2: new full-speed USB device number 22 using xhci_hcd
[ 6367.817010] usb 1-2: New USB device found, idVendor=313a, idProduct=0001
[ 6367.817017] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 6367.817022] usb 1-2: Product: SKYCOIN
[ 6367.817027] usb 1-2: Manufacturer: SkycoinFoundation
[ 6367.817031] usb 1-2: SerialNumber: 862E088D52307DBB88C75CD2
[ 6367.873780] hid-generic 0003:313A:0001.0006: hiddev1,hidraw3: USB HID v1.11 Device [SkycoinFoundation SKYCOIN] on usb-0000:00:14.0-2/input0
```

**Comment by stdevAlDen** [comment]
Hello @mpsido thank you very much, this was help me, pressing the button before 3 seconds make device working, now the kernel load correctly the device and create the `/dev/hidraw*` file. I was able to upload a firmware with the [go cli](https://github.com/skycoin/hardware-wallet-go/) tool trough the boot-loader but not with [`st-link`](https://github.com/texane/stlink) or `openocd`, do I need any special wire to use st-link software

**Comment by mpsido** [comment]
I am glad it worked for you
The st-link software is if you use a st-link, that is a device to flash STM32 microcontrollers, see the photo below.

You don't need it if there is already a bootloader running on your device.
![1125245901](https://user-images.githubusercontent.com/18638060/51536573-fd8f7900-1e86-11e9-89cf-6577b04f0a5b.jpg)

**Comment by mpsido** [comment]
@stdevAlDen if your questions are answered please close this issue

**Comment by stdevAlDen** [comment]
@mpsido thank you very much, I was receive a big help from you :1st_place_medal:
