### ISSUE TITLE
multiple security issues in the firmware, feedback requested

### ISSUE THREAD

**Issue by invd** [skycoin/hardware-wallet#56]
Hello Skycoin team,
I've discovered a number of issues including memory safety issues in your firmware code that I want to report to you confidentially.

Unfortunately, the security contact email `security@skycoin.net` that is stated in the README.md does not appear to be functional:

```
 <security@skycoin.net>: host mx.zoho.com[136.143.190.121] said: 550 5.1.1
    <security@skycoin.net> User unknown (in reply to RCPT TO command)
```

I've sent the PGP encrypted report to the `@protonmail.com` email address associated with your PGP pubkey (id ` 0x5801631BD27C7874`) instead. Over the last two weeks, I have not received any reply and have to assume that this is unreachable as well.

Please acknowledge the report (if you have received it) or provide an alternative, functional email contact for the disclosure.

**Comment by jdknives** [comment]
@invd Hey there. Thanks for this ticket. We have switched domains and this instance of the old domain must have slipped through the cracks. You can find the up to date infos here for sending a mail: https://github.com/SkycoinProject/skycoin#responsible-disclosure

**Comment by invd** [comment]
The new email address is also unreachable:
```
<security@skycoin.com>: host mx.zoho.com[136.143.190.121] said: 550 5.1.1
    <security@skycoin.com> User unknown (in reply to RCPT TO command)
```

**Comment by jdknives** [comment]
@invd sorry about the inconvenience but could you please try again? You must have sent the message minutes before the address was setup.
