### ISSUE TITLE
[Hardware-wallet] Fiber coin parameters

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#63]
Firmware should contain fiber coin params , and behavior should be consistent with coin parameters . This info could be read-only .

**Comment by Senyoret1** [comment]
I do not know if this is really necessary. As it works now, the hardware wallet does not have any specific information about the coin, it simply creates addresses and signs transactions with the algorithms used by Skycoin. The software wallet is responsible for selecting the inputs, creating the outputs, calculating the burn rate, etc. So at this moment the hardware wallet is in some way compatible with all Fiber coins.

**Comment by olemis** [comment]
That's a good idea . Sending that info on the wire is much better .

**Comment by olemis** [comment]
If sending on the wire is not feasible then feel free to reopen this issue .
