### ISSUE TITLE
Firmware versioning and release process

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#64]
- [x] A documented process is needed for managing the version number during development and for releases .
- [x] The release process should include the tagging of `skycoin/hardware-wallet-protob` to match message definitions .
- [x] Initial assignment of codes for combined firmware .

**Comment by jdknives** [comment]
We should be using semantic versioning for the firmware releases generally. Check this document for reference: https://semver.org/

**Comment by olemis** [comment]
In other projects we've a versioning model that resembles Skycoin . For instance PySkycoin's major and minor version numbers are exactly the same as Skycoin node's at release time . There is a source code dependency in that case , higher coupling than in here (desktop wallet => hw wallet)

**Comment by olemis** [comment]
Semantic version scheme for consecutive release builds of `tiny-firmware` is ok . Nonetheless for combined firmware I'd rather prefer an scheme that considers.

- **Bootloader version**: bootloader version identifier
- **Firmware version**: identifier for tiny-firmware version number
- **SoC chip** MCU model identifier.
- **Country Exit Code**: to cope with i18n and locale specific features

**Comment by olemis** [comment]
Once skycoin/hardware-wallet-protob#4 will be merged , firmware release implies tagging `skycoin/hardware-wallet-protob` to match versions .

**Comment by olemis** [comment]
@gz-c combined firmware versioning scheme should consider locale and regional settings . Will we ever have more than 32 officially supported target languages ? Officially supported means for mainstream milestone releases .

**Comment by olemis** [comment]
> Will we ever have more than 32 officially supported target languages ?

We shall focus on [supported BIP39 word lists](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md).

**Comment by olemis** [comment]
fixed in 5860c3e
