### ISSUE TITLE
Request confirmation to sign generic messages

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#77]
**Feature description**
The hardware wallet has a function that allows to sign generic messages. Previously the function was used to sign transactions and the user was not requested for confirmation due to several UX reasons, but now there is a function that allows to sign complete transactions, so the function that signs generic messages will not be used in the integration with the desktop wallet any more (the change is in https://github.com/skycoin/skycoin/pull/2156). Due to this change, now it would be good to modify the function that signs generic messages to make it ask the user for confirmation.

**Is your feature request related to a problem? Please describe.**
Requesting confirmation would increase security, since it would not be possible for malicious software to sign messages with the conneted hardware wallet without the user's approval.

**Describe the solution you'd like**
While asking for confirmation, the hardware wallet screen may show the message that will be signed. The operation could be similar to the function that allows signing transactions.

**Describe alternatives you've considered**
Another alternative could be to delete the function that allows to sign generic messages, since at the moment it would not be used. However, it may be useful in the future.

**Comment by jdknives** [comment]
Can this simply be deactivated for v1.0.0?

**Comment by Senyoret1** [comment]
I guess so, I think the function is not used for anything, at least for now.

**Comment by jdknives** [comment]
OK. Then this should be done.

**Comment by olemis** [comment]
> Requesting confirmation would increase security, since it would not be possible for malicious software to sign messages with the conneted hardware wallet without the user's approval.

Message signing is protected by PIN .

**Comment by stdevStark** [comment]
@olemis why buttons can not be pushed in 2be2842 ?

**Comment by olemis** [comment]
@stdevStark I do not understand your question ...

**Comment by olemis** [comment]
> @olemis why buttons can not be pushed in [2be2842](https://github.com/skycoin/hardware-wallet/commit/2be2842d6ad185aeca226fb486daa2e843bcc1dd) ?

i am not sure

**Comment by stdevStark** [comment]
> i am not sure

see skycoin/hardware-wallet-js#114

**Comment by olemis** [comment]
fixed in 160614a
