### ISSUE TITLE
Allow to create transactions with more than 8 inputs and 8 outputs

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet#79]
**Feature description**
At this time, if the function to create transactions added in https://github.com/skycoin/hardware-wallet/pull/62 is called with more than 8 inputs or 8 outputs, it fails with `Error: array overflow` (at least when being called from the JS library). It would be good if the function allow many more inputs/outputs.

**Comment by olemis** [comment]
@Senyoret1 thanks for creating this issue . I'll take a look into this asap

**Comment by jdknives** [comment]
This is not part of Milestone 1.0.0 and should therefore not be further pursued at this time.
