### ISSUE TITLE
Unable to check signature of message

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#80]
**Describe the bug**
Unable to [check as valid](https://github.com/simelo/skycoin-hardware-wallet/blob/ca351ae5f6615764e6bf0ed1b42cb1f76e50d063/tiny-firmware/firmware/fsm_impl.c#L142) the signature of a [signed hash](https://github.com/simelo/skycoin-hardware-wallet/blob/ca351ae5f6615764e6bf0ed1b42cb1f76e50d063/tiny-firmware/firmware/fsm_impl.c#L61).

**Environment information:**

- Travis GNU/Linux (https://travis-ci.com/skycoin/hardware-wallet/jobs/176918013#L2131).
- Travis Mac (https://travis-ci.com/skycoin/hardware-wallet/jobs/176918014#L1948).

**Steps to Reproduce**
- There is currently [a test](https://github.com/simelo/skycoin-hardware-wallet/blob/ca351ae5f6615764e6bf0ed1b42cb1f76e50d063/tiny-firmware/firmware/test_fsm.c#L84) that catch the problem.

**Actual behavior**
Unable to check the original address that sign the message.

**Expected behavior**
Signing a message with and address have to be confirmed with this address.

Additional resources:
https://github.com/skycoin/skycoin/blob/develop/src/cipher/testsuite/testdata/input-hashes.golden

**Comment by olemis** [comment]
closed by ` [5c2a9d2](/skycoin/hardware-wallet/commit/5c2a9d266748408c1e827127829df4c488985de8)`
