### ISSUE TITLE
Integer error codes

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet#81]
**Feature description**

Integer error codes

**Is your feature request related to a problem? Please describe.**
All functions in `fsm_impl.c` return `ErrFailed` , hence test code can not determine the cause of failure when multiple error modes might be expected to happen .

**Describe the solution you'd like**
Interger error codes reflecting what part of the source code failed and the nature of the failure .

**Comment by jdknives** [comment]
This issue does not specify a whole lot. Either it needs to be closed or the problem needs to be described. @olemis

**Comment by olemis** [comment]
> This issue does not specify a whole lot. Either it needs to be closed or the problem needs to be described. @olemis

Sorry , did not notice once I created the issue .
This is already implemented in `error.h`
