### ISSUE TITLE
Unable to hit commands to the device with js tool after using the golang one.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#82]
**Describe the bug**
After using the golang tool to send command to the device is required to unplug the device and plug in it again.

**Environment information:**
- Linux hostname 4.19.0-1-amd64 1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux
- node --version v10.15.1
- go version go1.11.5 linux/amd64
- [hardware-wallet](https://github.com/skycoin/hardware-wallet) HEAD -> e418401d19bc03ce4a366550e479c7bf487632cf
- [hardware-wallet-js](https://github.com/skycoin/hardware-wallet-js) HEAD -> 21a9941e9a65d322a6795106c22cfc8553d95b09
- [hardware-wallet-go](https://github.com/skycoin/hardware-wallet-go) HEAD -> d6f59ef9d96b18b523653f5e7ef99bc93f9d99a9
- Firmware Version: 1.7.0

**Steps to Reproduce**
- Plug in the device
- run `hardware-wallet-go deviceGetVersion`
- npm start

> hardware-wallet-js@1.0.0 start /mnt/WORK/SkyCoin/hardware-wallet-js
> node main.js

dev 46d / c077 : usage_page:d263, usage:c4fc
Skycoin hardware NOT FOUND, using emulator
Device Open
Sending data <Buffer 3f 23 23 00 05 00 00 00 00 0a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... > 64
Sending data 64
.
.
. keep waiting for ever without communication

**Actual behavior**
Loses hw-js comunication after use hw-go

**Expected behavior**
Should be able to communicate with any of hw-go or hw-js 

**Additional context**
This only happens with the physical device, not with the emulator

**Possible implementation**
None, is required to get in deep to know more...

**Comment by jdknives** [comment]
Outdated as the js interface is to be deprecated.
