### ISSUE TITLE
Incomplete line in screen.

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/hardware-wallet#83]
**Describe the bug**
maybe there is an incomplete line in the screen
![hw-device](https://user-images.githubusercontent.com/34870496/52664979-62fbe600-2ed8-11e9-9199-b923b9c77bd5.jpg)

**Environment information:**
Device loader 1.4.0

**Steps to Reproduce**
- Plug in the device with both buttons pressed.
- Upload a new firmware through the boot loader `hardware-wallet-go deviceFirmwareUpdate`
- Confirm twice.

**Comment by olemis** [comment]
fixed in b894b63
