### ISSUE TITLE
GetVersion does not return the firmware version

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet#98]
**Describe the bug**
The `GetVersion` message does not return the firmware version instead it returns `success`(?)

**Actual behavior**
Returns success

https://github.com/skycoin/hardware-wallet/blob/39229d610a4f8d68d9f4f30921fd9667ea52b4b7/tiny-firmware/protob/messages.proto#L307-L312

**Expected behavior**
Return firmware version

**Comment by stdevAlDen** [comment]
@therealssj & @olemis 
I recommend remove this message and use [`Featres`](https://github.com/skycoin/hardware-wallet/blob/39229d610a4f8d68d9f4f30921fd9667ea52b4b7/tiny-firmware/protob/messages.proto#L100-L102) instead, in addition write a unit tests for this, what do you think?

**Comment by olemis** [comment]
@therealssj indeed these are the right values to consider

https://github.com/skycoin/hardware-wallet/blob/39229d610a4f8d68d9f4f30921fd9667ea52b4b7/tiny-firmware/protob/messages.proto#L84-L86

They contain the version numbers of the feature in use (either bootloader or firmware). The ones mentioned above by @stdevAlDen are to report firmware version number when in bootloader mode.

**Comment by olemis** [comment]
`GetVersion` message was added in 7fe699d9 and has not changed much since then . Does not seem to be at all useful. If we all agree I'm keen of removing it.

This is low priority though . Not a reason for blocking first release .

**Comment by olemis** [comment]
On the other hand @therealssj , success message has a text field . That's enough for returning firmware version back to the connected peer. That's the reason why there is no specific message to reply to `GetVersion` requests.

**Comment by stdevStark** [comment]
@olemis fixed in f351c5f but issue not closed
