### ISSUE TITLE
Hardware models ?

### ISSUE THREAD

**Issue by cryptoida** [skycoin/hardware-wallet#99]
On which hardware model(s) , can be installed this firmware?
Thank.

**Comment by jdknives** [comment]
@cryptoida On the hardware wallets provided by Skycoin. They will be sold as soon as the development for the release is done. Please check the ledger-nano repo for progress on the integration for Ledger Nano S.

**Comment by jdknives** [comment]
Also the project board and the Milestone 1.0.0 gives you an indication of the work that needs to be finished before release of the Skycoin Hardware Wallets.
